### ISSUE TITLE
Noting a couple typos

### ISSUE THREAD

**Issue by seanchen1991** [Michael-F-Bryan/adventures.michaelfbryan.com#1]
Hi Michael,

I really loved your post on implementing `ArrayVec` using const generics. Here are a few typos I noticed:

1. In the code snippet for the `pop` implementation, in the doc test comments, you have 
`/// # use const_arrayvec::ArrayVec;`. Specifically, the `#` seems out of place, though I suppose that could also could have some meaning in doc tests that I'm not aware of. 

2. In the code snippet for the `truncate` implementation, there's no `use core::slice;` at the top of the snippet when there should be one to use `slice::from_raw_parts_mut()`. 

3. In the code snippet for the `From` trait implementation, the usage of `mem::forget(other);` doesn't work unless there is also a `use core::mem::{self};` at the top. 

4. The code snippet for the `Drain` trait isn't properly indented. 

5. The `impl Iterator for Drain` code snippet has some typos in its comments that are not easily discernible. 

6. It looks like you have the implementation for `size_hint` for `Drain` in two separate code snippets: one in the `Iterator for Drain` snippet and again in the `ExactSizeIterator` snippet. 

7. The code for the `Drain` struct looks like it needs to be updated. There are some fields you use later on in other snippets that make use of fields on the `Drain` struct that you didn't have defined in the initial snippet. 

8. There is no `use core::iter::{DoubleEndedIterator, FusedIterator};` statement in any of the snippets when you start implementing `Drain`. 

9. Not sure if this was intentional or an oversight, but the `impl Drain` code snippet at the very end is never really talked about, yet you elude to it by showcasing some of the code, but not all of it. 

Anyways, sorry if this comes off as overly pedantic, but I really like this post and would like to see it in as polished a state as possible. Cheers!

**Comment by Michael-F-Bryan** [comment]
> Specifically, the # seems out of place, though I suppose that could also could have some meaning in doc tests that I'm not aware of.

That's correct, adding a `#` to the start of a line will [tell `rustdoc` not to show that line](https://doc.rust-lang.org/rustdoc/documentation-tests.html#hiding-portions-of-the-example) by default.

> In the code snippet for the truncate implementation, there's no use core::slice; at the top of the snippet when there should be one to use slice::from_raw_parts_mut().

> In the code snippet for the From trait implementation, the usage of mem::forget(other); doesn't work unless there is also a use core::mem::{self}; at the top.

> There is no use core::iter::{DoubleEndedIterator, FusedIterator}; statement in any of the snippets when you start implementing Drain.

Good point. Looking back, I wasn't overly consistent with when I'd mention an import and when I wouldn't. I did another skim through and *think* I've got all of them.

> It looks like you have the implementation for size_hint for Drain in two separate code snippets

Oops! That first `size_hint()` shouldn't be there. It's only meant to be added when `ExactSizedIterator` is implemented. Nice catch!

> Not sure if this was intentional or an oversight, but the impl Drain code snippet at the very end is never really talked about, yet you elude to it by showcasing some of the code, but not all of it.

Thanks, I'd rewritten `Drain`'s constructor several times and it looks like I forgot to add the final version to the blog post.

---

Thanks for taking the time to spot these issues/bugs and create a ticket @seanchen1991. I really appreciate having a second pair of eyes look through and do this sort of proofreading. The extra polish really makes a difference :slightly_smiling_face:

**Comment by Michael-F-Bryan** [comment]
@seanchen1991 I think everything has been addressed. If not, feel free to reopen the issue.
