### ISSUE TITLE
SVG image in words-are-hard post breaks site on mobile

### ISSUE THREAD

**Issue by maroider** [Michael-F-Bryan/adventures.michaelfbryan.com#10]
When the post is viewed on a device with a narrow enough screen, the SVG takes up more horizontal space than the viewport has. This makes the page scrollable in the horizontal direction. Everything else scales nicely.
The SVG can be found under the "Draw pretty pictures" heading.
The following snippet fixed the issue when I inserted it with Firefox Developer Tools:
```CSS
svg { max-width: 100%; }
```

**Comment by Michael-F-Bryan** [comment]
Thanks for pointing this out @maroider, the fix should be automatically applied as soon as CI finishes.
