### ISSUE TITLE
RSS/Atom feed

### ISSUE THREAD

**Issue by hannobraun** [Michael-F-Bryan/adventures.michaelfbryan.com#31]
Would it be possible to add an RSS/Atom feed to the website? I'm not familiar with Hugo, or I would look into it myself. I'm hoping it's an easy addition for someone who's already familiar.

**Comment by Michael-F-Bryan** [comment]
The website should already have RSS wired up (http://adventures.michaelfbryan.com/index.xml), but I don't think the theme I'm using actually displays a clickable link for it.

It also doesn't help that I haven't published anything since July.

**Comment by hannobraun** [comment]
Nice, that works! I think I tried every combination of [/posts]/{rss.xml|atom.xml}, so I thought there wasn't one :-)

Tip: You can add something like the following snippet to your HTML, then people should be able to just paste the page URL into their RSS reader, instead of having to find the RSS link manually: https://github.com/hannobraun/madeby.hannobraun.de/blob/9244f63d8c9763e7bb5ff923f7cc06cbf77cba5f/templates/extend/base.html#L16

I'm leaving this open, in case you want to track any of the further improvements mentioned here, but as far as I'm concerned, the problem is solved. Thanks!

**Comment by Michael-F-Bryan** [comment]
It looks like Hugo was already adding `<link rel=alternate type=application/rss+xml href=https://adventures.michaelfbryan.com/index.xml title=Michael-F-Bryan>` to the website's `<head>` tag. Forcing people to view the page source and find the correct tag so they can copy a link isn't overly satisfactory, though.

I did a bit more digging and it was really easy to add an RSS icon to the front page (see 7cc44f1). I think that should round out the story around RSS.

**Comment by hannobraun** [comment]
I could have sworn I tried pasting the page URL into my RSS, but I probably mixed something up. In any case, thanks for the changes!
