### ISSUE TITLE
Source code blocks are illegible in dark theme

### ISSUE THREAD

**Issue by TheDestroyer19** [Michael-F-Bryan/adventures.michaelfbryan.com#43]
In Dark Mode:

![image](https://user-images.githubusercontent.com/17345449/120521372-bcc69980-c389-11eb-9a4b-e8b3cc118180.png)

In Light Mode:

![image](https://user-images.githubusercontent.com/17345449/120521666-d49e1d80-c389-11eb-8a91-eb86c7182687.png)

**Comment by Michael-F-Bryan** [comment]
That sounds like https://github.com/luizdepra/hugo-coder/issues/567. I'll see if I can use a different colour scheme that works better.
