### ISSUE TITLE
Fibonacci iterator and "missing"

### ISSUE THREAD

**Issue by trentj** [Michael-F-Bryan/adventures.michaelfbryan.com#50]
From the Iterators installment:

> We actually miss the top two Fibonacci numbers using the above `Iterator` implementation,

I don't believe this is true: the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5ecf8f52253983fabe7b24edc2ed6c8d) emits all the Fibonacci numbers up to F<sub>47</sub>, which is the greatest one less than 2<sup>32</sup>. Possibly this is a stale note left over from an earlier draft?

**Comment by Michael-F-Bryan** [comment]
Good catch! You were 100% correct.

In my previous version, `next_term` would always be lagging the yielded value by two iterations because my starting conditions were `Fibonacci { first: 1, second: 1 }` and we would yield `self.first`.

```rust
#[derive(Debug)]
struct Fibonacci {
    first: u32,
    second: u32,
}

impl Iterator for Fibonacci {
    type Item = u32;

    fn next(&mut self) -> Option<u32> {
        let Fibonacci { first, second } = *self;

        let next_term = first.checked_add(second)?;

        self.first = second;
        self.second = next_term;

        Some(first)
    }
}

fn fibonacci_numbers() -> Fibonacci {
    Fibonacci {
        first: 1,
        second: 1,
    }
}

fn main() {
    for number in fibonacci_numbers() {
        println!("{}", number);
    }
}
```
