### ISSUE TITLE
[Daily Rust: Slice Patterns] article, palindrome example playground test error

### ISSUE THREAD

**Issue by alexanderlin** [Michael-F-Bryan/adventures.michaelfbryan.com#51]
With current playground link tests cannot find `word_is_palindrome` function. Need to add `use super::*;` into test module, I added it into this playground [link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a4adf1c312c65c47a5d8975cba45a1de) for convenience.

**Comment by Michael-F-Bryan** [comment]
Thanks for catching this @alexanderlin! 

I'm guessing I used an old version of the playground program and forgot to update the link after checking that the tests passed.
